### ISSUE TITLE
Provide explanation for file and directory naming conventions

### ISSUE THREAD

**Issue by yotkadata** [mhkeller/layercake-template#23]
This a a great project - thanks so much for the work put into it!

I am having trouble understanding the file and directory naming conventions, though. The layercake-template has this structure in `src/`:

```
├── app.css
├── app.html
├── global.d.ts
└── routes
    ├── _components
    │   ├── Area.svelte
    │   ├── AxisX.svelte
    │   ├── AxisY.svelte
    │   └── Line.svelte
    ├── _data
    │   └── points.csv
    ├── +layout.js
    ├── +layout.svelte
    └── +page.svelte
```

Yet in the documentation/guide at https://layercake.graphics/guide, `App.svelte` is mentioned many times. There are also references to `<!-- { filename: './components/Scatter.svelte' } -->` (for example) instead of `_components` (note the underscore).

Could you provide some explanation in the Guide and/or README on file naming in the template? I have also searched for the reasons for plus signs (as in `+page.svelte`) and underscores (as in `_components`) in file and directory names.

I have been working in `+page.svelte` as if it was my `App.svelte`, but I'm not sure if that is the idea. Or are those files mere examples?

**Comment by yotkadata** [comment]
Ok, I wasn't aware that this comes from SvelteKit:
https://kit.svelte.dev/docs/routing

Still, it might be an improvement to mention it in the docs and maybe change the examples.

**Comment by mhkeller** [comment]
The docs were written before sveltekit so hence some differences. I can go through and make some updates where things are outdated although it's tricky because the current setup is not wrong per se. 

For example, you don't have to put your chart in `+page.svelte` and it would actually be more common to put your chart in some other component, hence the generically named `App.svelte`

The docs though were set up to show the basic concepts and not be super prescriptive or rigid. I could see adding the underscore to the `components` folder would make it seem like that is The Right Way To Do It, when that is not the case.

For example, one sveltekit convention is to put your components in the lib folder and then import them via `$lib/path/to/Component.svelte`. Layer Cake has no opinion about where you load your components from.

**Comment by yotkadata** [comment]
Thanks for the explanation Michael, I get it now. Maybe the easiest way would be to just mention that the template is based on SvelteKit which comes with its own directory structure (and then a link to https://kit.svelte.dev/docs/routing) as opposed to other ways Svelte is used. I suppose that would have helped me to understand quicker.

Keep up the great work!

**Comment by mhkeller** [comment]
Sorry this took so long. I added a link and reference to SvelteKit in the readme
